# Generated by Django 4.2.16 on 2026-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_ttS_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
