# Generated by Django 4.2.16 on 2026-08-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('students_trained', 'Students Trained'), ('placements', 'Placements'), ('years_of_experience', 'Years of Experience'), ('placement_rate', 'Placement Rate'), ('average_package', 'Average Package'), ('hiring_partners', 'Hiring Partners')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(help_text="Display value, e.g. '1000+', '92%', '₹4.2L'", max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Statistic',
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['order'],
            },
        ),
    ]
