# Generated by Django 4.2.16 on 2026-08-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('code', models.CharField(db_index=True, help_text='Short language code, e.g. EN, KN, TE', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. English', max_length=50)),
                ('native_name', models.CharField(blank=True, help_text='Name in its own script, e.g. ಕನ್ನಡ', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
